// ── Layout Analysis Types ─────────────────────────────────────────────────────

export interface LayoutAnalysisResult {
  reference_summary: {
    content_type: string;
    best_use_cases: string[];
    overall_mood: string[];
  };
  canvas: {
    detected_ratio: '4:5' | '1:1' | '9:16' | string;
    recommended_width: number;
    recommended_height: number;
  };
  global_style: {
    palette: {
      background: string;
      text: string;
      accent: string;
      [key: string]: string;
    };
    typography: {
      headline: { style: string; estimated_size: number; weight: number };
      body: { style: string; estimated_size: number; weight: number };
      accent?: { style: string; estimated_size: number; weight: number };
    };
    spacing: { outer_margin: number; section_gap: number };
  };
  slides: SlidePattern[];
  template_rules: {
    text_density: 'low' | 'medium' | 'high';
    image_dependency: 'low' | 'medium' | 'high';
    recommended_slide_count: number;
    safe_area_policy: string;
  };
}

export interface SlidePattern {
  slide_no: number;
  role: SlideRole;
  layout_type: LayoutType;
  zones: TemplateZone[];
}

export type SlideRole =
  | 'cover' | 'intro' | 'problem' | 'solution'
  | 'tip' | 'offer' | 'cta' | 'info' | 'closing';

export type LayoutType =
  | 'full_bleed_photo'
  | 'full_bleed_photo_bottom_text'
  | 'full_bleed_photo_top_text'
  | 'text_only'
  | 'split_text_image'
  | 'card_stack'
  | 'centered_headline'
  | 'product_focus'
  | 'info_grid';

// ── Template Zone ─────────────────────────────────────────────────────────────

export interface TemplateZone {
  id: string;
  type: 'text' | 'image' | 'shape' | 'logo' | 'cta';
  role?: 'headline' | 'subcopy' | 'body' | 'caption' | 'price' | 'button';
  x: number;
  y: number;
  w: number;
  h: number;
  style?: {
    fontSize?: number;
    fontWeight?: number;
    color?: string;
    backgroundColor?: string;
    radius?: number;
    align?: 'left' | 'center' | 'right';
    lineHeight?: number;
    opacity?: number;
  };
}

// ── Template JSON (재사용 자산) ────────────────────────────────────────────────

export interface TemplateJSON {
  version: number;
  canvas: { width: number; height: number; ratio: string };
  globalStyle: LayoutAnalysisResult['global_style'];
  slides: SlidePattern[];
  rules: LayoutAnalysisResult['template_rules'];
  tags?: { industry?: string[]; purpose?: string[]; mood?: string[]; layout?: string[] };
}

// ── Canvas Editor Layer JSON ───────────────────────────────────────────────────

export type CanvasLayer =
  | { id: string; type: 'image'; src: string; x: number; y: number; w: number; h: number; locked?: boolean; opacity?: number }
  | {
      id: string; type: 'text'; text: string; x: number; y: number; w: number; h: number;
      fontFamily?: string; fontSize?: number; fontWeight?: number;
      color?: string; lineHeight?: number; align?: string; locked?: boolean;
    }
  | { id: string; type: 'shape'; shape: string; x: number; y: number; w: number; h: number; fill?: string; stroke?: string; radius?: number };

export interface EditableJSON {
  canvas: { width: number; height: number };
  layers: CanvasLayer[];
}

// ── Project Input ─────────────────────────────────────────────────────────────

export interface GenerationInput {
  templateId: string;
  brandId?: string;
  topic: string;
  businessType?: string;
  goal?: string;
  target?: string;
  offer?: string;
  clientContext?: string;
  slideCount?: number;
}

// ── Slide Content (generated by GPT) ─────────────────────────────────────────

export interface SlideContent {
  slideNo: number;
  role: SlideRole;
  headline?: string;
  subcopy?: string;
  body?: string | null;
  items?: string[] | null;
  cta?: string | null;
  imagePrompt?: string;
}

// ── Reference Image ───────────────────────────────────────────────────────────

export interface ReferenceImage {
  id: string;
  url: string;
  width?: number;
  height?: number;
  base64?: string;
}
